plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator" 
  - - "@semantic-release/exec"
    - verifyReleaseCmd: "echo ${nextRelease.version} > VERSION.txt"
  - "@semantic-release/gitlab"


branches:
  - "master"
  - name: "staging"
    prerelease: "pre"
  - name: "testing"
    prerelease: "test"
  - "+([0-9])?(.{+([0-9]),x}).x"
  - name: "dev"
    prerelease: "dev"
